### ISSUE TITLE
"Unable to load the structure of a folder." error

### ISSUE THREAD

**Issue by jfquestiaux** [Quantum-Manager/tracker#178]
Hi.
I have this error when I try to access images in Quantum Manager.
This must be related with the server because it was working fine on the dev server. Does not work on the production server but I have no idea where to look to debug this.

Hint: the Joomla media manager does not work either. It gives this error: 
Property 'mime_type' of argument 'item' of event onFetchMediaItems has a wrong item. Valid: string

A PHP module missing?

Server Litespeed
PHP 8.1.18
Joomla 4.3.2
Quantum Manager 2.0.2

Thanks for any help.

**Comment by jfquestiaux** [comment]
OK. The "fileinfo" PHP module was disabled. Enable it solves the issue.

**Comment by Sulpher** [comment]
Bonjour Jean-François !
Sorry for the delay. A nice to see you have found and resolved the issue.

Have a good week!

**Comment by web54** [comment]
I have the same error, and at least,file info is enabled

**Comment by Sulpher** [comment]
> I have the same error, and at least,file info is enabled

More info is needed.

**Property 'mime_type' of argument 'item' of event onFetchMediaItems has a wrong item. Valid: string**

do you have this error?

**Comment by web54** [comment]
no, i do not.
but in console I have : 
index.php:1 Uncaught SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Object.done (quantumtreecatalogs.js?1692717047:64:29)
    at ajax.request.onreadystatechange (utils.js?1692717047:137:30)

**Comment by Sulpher** [comment]
[web54](https://github.com/web54) 
I suppose there might be problems with permissions or it might be a problem with wrong file names.
Do you have this error everywhere, in each folder? can you proceed to another folder and see the list of files?
Try to set the same owner to /images/ folder and its subfolders and files and 755 to folders and 644 to files inside these folders. 

This is another issue which is not related to this topic. One issue - one topic for keeping all questions structured. 
If my advice above could not help, then please open a new issue and provide all details: Joomla and Quantum version, make sure all component libraries are installed and etc.

**Comment by web54** [comment]
well,
it won't be necessary, I've resolved.
the problem was that users had entered files with utf8 accents: French accents like é à or è.
Not really my fault, as I trained the first users, but not the replacements, but I should have blocked this possibility.
Thanks for all

**Comment by Sulpher** [comment]
[web54](https://github.com/web54), Quantum has an option to convert diacritical symbols to the standards according to localization file and this option is disabled by default. 
<img width="774" alt="Снимок экрана 2023-08-23 в 10 43 09" src="https://github.com/Quantum-Manager/tracker/assets/3432048/0cc9918b-ddd5-4528-989b-7e16aafad000">
If it is disabled, then when you upload a file that contains diacritical symbols, it'll be converted to the right format.
But the users should upload files via Quantum Manager. 
So, it's nice to hear the problem is resolved.
If you like  Quantum, we'd be happy to see your short testimonial at the JED or at Trustpilot. Thanks.
